// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC02E-AdHRgLr9Nuj6Ot-4Jbh8BibqM94c',
    appId: '1:1082099337478:web:12201eae62e2901523b687',
    messagingSenderId: '1082099337478',
    projectId: 'surfwall',
    authDomain: 'surfwall.firebaseapp.com',
    storageBucket: 'surfwall.firebasestorage.app',
    measurementId: 'G-Y867MTFHHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEMNqDb3j4FnA6cT0fvuelbvb87iMyKLU',
    appId: '1:1082099337478:android:7d8c47c1999bfbe023b687',
    messagingSenderId: '1082099337478',
    projectId: 'surfwall',
    storageBucket: 'surfwall.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPEaOC9iuQq0ZBkTwb6duzDxsox6SKL8o',
    appId: '1:1082099337478:ios:f8c3a857e17d96b223b687',
    messagingSenderId: '1082099337478',
    projectId: 'surfwall',
    storageBucket: 'surfwall.firebasestorage.app',
    iosClientId: '1082099337478-ijpuopskljj3nlgm8mn3os968v74pljj.apps.googleusercontent.com',
    iosBundleId: 'com.example.surfWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPEaOC9iuQq0ZBkTwb6duzDxsox6SKL8o',
    appId: '1:1082099337478:ios:f8c3a857e17d96b223b687',
    messagingSenderId: '1082099337478',
    projectId: 'surfwall',
    storageBucket: 'surfwall.firebasestorage.app',
    iosClientId: '1082099337478-ijpuopskljj3nlgm8mn3os968v74pljj.apps.googleusercontent.com',
    iosBundleId: 'com.example.surfWall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC02E-AdHRgLr9Nuj6Ot-4Jbh8BibqM94c',
    appId: '1:1082099337478:web:6b5e1ee11e9af04f23b687',
    messagingSenderId: '1082099337478',
    projectId: 'surfwall',
    authDomain: 'surfwall.firebaseapp.com',
    storageBucket: 'surfwall.firebasestorage.app',
    measurementId: 'G-0N8N68NQ2T',
  );
}
